# Generated by Django 2.2.6 on 2019-10-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('User_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre_Usuario', models.CharField(max_length=45)),
                ('Username', models.CharField(max_length=45)),
                ('Correo_Usuario', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=32)),
                ('Super_User', models.CharField(max_length=1)),
                ('Direccion_Residencia', models.CharField(max_length=45)),
            ],
        ),
    ]
